# syntax=docker/dockerfile:1.7
FROM golang:1.24-bookworm AS builder
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
# Build worker executable
RUN CGO_ENABLED=0 go build -o /out/tirtapp-worker ./cmd/worker/main.go

FROM debian:bookworm-slim
WORKDIR /app
COPY --from=builder /out/tirtapp-worker .
# Salin juga file service account
COPY ./secret/firebase-service-account.json . 
CMD ["./tirtapp-worker"]