services:
  # --- Layanan API Anda ---
  tirtapp-api:
    image: darmawiguna/tirtapp-api:latest # Nama image API
    container_name: tirtapp-api-prod
    restart: always
    ports:
      - "127.0.0.1:8095:8080"
    env_file:
      - ./.env
    depends_on:
      mysql-db:
        condition: service_healthy
      rabbitmq:
        condition: service_started # RabbitMQ 3+ starts quickly, 'started' is usually sufficient

  # --- [BARU] Layanan Worker ---
  tirtapp-worker:
    image: darmawiguna/tirtapp-worker:latest # Nama image Worker
    container_name: tirtapp-worker-prod
    restart: always
    env_file:
      - ./.env
    volumes:
      # Mount file secret dari host ke dalam container worker
      # Pastikan file ./secrets/firebase-service-account.json ada di VPS
      - ./secrets/firebase-service-account.json:/app/secrets/firebase-service-account.json:ro
    depends_on:
      mysql-db:
        condition: service_healthy
      rabbitmq:
        condition: service_started

  # --- Layanan Database MySQL ---
  mysql-db:
    image: mysql:8.0
    # ... (konfigurasi mysql tidak berubah) ...
    volumes:
      - db-data:/var/lib/mysql

  # --- Layanan Message Queue RabbitMQ ---
  rabbitmq:
    image: rabbitmq:3-management # Gunakan image resmi, pastikan setup DLX di code Go benar
    container_name: tirtapp-rabbitmq
    # ... (konfigurasi rabbitmq tidak berubah) ...
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/

volumes:
  db-data:
  rabbitmq-data: